## WRITE YOUR DOCKER COMPOSE HERE!
version: '3.9'

services:
  postgres_container:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=psql_docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 6000:5432

  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
      - 4444:4444
    depends_on:
      - postgres_container
